sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - npm i -g npm@^6.5.0
before_script:
  - npm prune
script:
  - npm run lint
  - npm test
