version: "3"

services:
  database:
    build: ./database/postgres
    container_name: docker-multistage-demo-database
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=postgres-password"
      - "POSTGRES_DB=postgres-db"
    volumes:
      - ./database/postgres/sql/:/docker-entrypoint-initdb.d/
      - ./database/postgres/postgres/data/:/var/lib/postgresql/data/
      - ./database/postgres/postgres/logs/postgres/:/var/log/postgres/
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - "NODE_ENV=production"
    networks:
      - docker-multistage-demo-connect
    depends_on:
      - database
  frontend:
    image: nginx:alpine
    container_name: docker-multistage-demo-frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend/static:/usr/share/nginx/html
    networks:
      - docker-multistage-demo-connect
    depends_on:
      - database
      - backend

networks:
  docker-multistage-demo-connect:
    driver: bridge
