# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-test-install-deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/project/myproject

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # - run: apk update && apk add --no-cache git
      # - run: ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}

      # run tests!
      - run: npm run lint:eslint
      - run: npm run lint:prettier
      - run: npm run test

workflows:
  version: 2
  build-test-install-deploy-test:
    jobs:
      - build-test-install-deploy:
          context: myproject-test
          filters:
            branches:
              only:
                - development
  build-test-install-deploy-prod:
    jobs:
      - build-test-install-deploy:
          context: myproject-prod
          filters:
            branches:
              only:
                - master
