version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: docker-fullstack-app-multistage-demo-backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      - 'NODE_ENV=development'
    networks:
      - docker-fullstack-app-multistage-demo-connect
    volumes:
      - ./backend/app:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
  frontend:
    image: nginx:alpine
    container_name: docker-fullstack-app-multistage-demo-frontend
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend/static:/usr/share/nginx/html
    networks:
      - docker-fullstack-app-multistage-demo-connect
    depends_on:
      - backend

networks:
  docker-fullstack-app-multistage-demo-connect:
    driver: bridge
