version: '3'

services:
  backend:
    build: ./backend
    container_name: docker-fullstack-app-multistage-demo-backend
    ports:
      - '3000:3000'
    environment:
      - 'NODE_ENV=production'
    networks:
      - docker-fullstack-app-multistage-demo-connect
  frontend:
    image: nginx:1.17-alpine
    container_name: docker-fullstack-app-multistage-demo-frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend/static:/usr/share/nginx/html
    networks:
      - docker-fullstack-app-multistage-demo-connect
    depends_on:
      - backend

networks:
  docker-fullstack-app-multistage-demo-connect:
    driver: bridge
