# Can be connected via url mongodb://mongo_user:mongo_pass@127.0.0.1:27017
version: '3'

services:
  mongo:
    container_name: mongo-db-template
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
    ports:
      - '27017:27017'
    volumes:
      - mongo:/var/lib/mongo
    networks:
      - mongo-connect

volumes:
  mongo: ~

networks:
  mongo-connect:
    driver: bridge
