# Can be connected via url redis://0.0.0.0:6379
version: '3.1'

services:
  redis:
    container_name: redis-db-template
    restart: always
    build: ./redis/
    ports:
      - '6379:6379'
    volumes:
      - ./redis/data/:/var/lib/redis
      - ./logs/redis/:/var/log/redis/
    networks:
      - redis-connect

networks:
  redis-connect:
    driver: bridge
